code/modules/mining/mine_items.dm
See the title. 100% tested and verified. Proof that it works below.
https://my.mixtape.moe/dugaez.webm
=> Can no longer use bluespace capsules on station

interface/interface.dm
Tested it and it succesfully works. So that's that.
=> Adds the Github Reporter

code/modules/mob/living/simple_animal/friendly/cat.dm
:cl: PopNotes
add: Emagging Runtime causes something great to happen.
/:cl:
=> Emagging Runtime makes her explode.

code/modules/mob/living/simple_animal/friendly/cat.dm, hippiestation.dme, hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
:cl: PopNotes
tweak: Made emagging Runtime more better.
/:cl:
Runtime actually causes a bit of damage when she explodes.
Though not even as much as a 100u/100u Potassium/Water grenade, it's still a feasible way of killing a few people. Hilariously.
=> Exploding Runtime - Updated and Modularized!

hippiestation/code/modules/reagents/reagent_dispenser.dm
:cl: PopNotes
tweak: chemtanks are back to the way they used to be at 1000u capacity
/:cl:
Ree
300u chemtanks are bad, let's bring 'em back to the good old days of glorious 1000u
=> BUFFS TANX

hippiestation/code/modules/projectiles/projectile/bullets.dm
:cl: PopNotes
balance: Revolver now has armor penetration. Use those shots wisely.
/:cl:
=> Gives the revolver armor penetration to compensate for nerfs

_maps/map_files/HippieStation/hippiestation.dmm
:cl: Pyko
fix: Fixes the Ai turret controllers
/:cl:
Fixes: https://github.com/HippieStation/HippieStation/issues/2908
=> Ai turret fix

code/game/objects/items/devices/flashlight.dm
:cl: PopNotes
balance: Seclites are now robust as advertised.
/:cl:
=> Seclites are now robust as advertised.

hippiestation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm, hippiestation/code/modules/reagents/chemistry/recipes/toxins.dm
:cl: PopNotes
add: Adds glucosaryll, a toxin that loads you up with unreasonable amounts of sugar.
/:cl:
I've always wanted a viable way to send people into hyperglycemic shock and now my dreams have become reality.
=> Adds Glucosaryll

hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm, hippiestation/code/modules/reagents/chemistry/recipes/drugs.dm
:cl: PopNotes
add: Added powder that makes you say yes. I am sorry.
/:cl:
=> Adds powder that makes you say yes

hippiestation.dme, hippiestation/code/game/objects/items/weaponry.dm
:cl: PopNotes
add: SORD now has a chance to crit for massive damage.
/:cl:
=> SORD now has a chance to crit for massive damage.

hippiestation/code/game/objects/structures/watercloset.dm
:cl: PopNotes
fix: Fixed the rubber duck honking people instead of quacking them.
/:cl:
=> EMERGENCY DUCK FIX

hippiestation/code/modules/mob/living/carbon/human/emote.dm
:cl: PopNotes
fix: Farts were too quiet before. That's fixed.
/:cl:
=> Makes farts less quiet

hippiestation/code/modules/client/preferences.dm
:cl: Pyko
add: More character slots.
/:cl:
=> Adds more character slots

_maps/map_files/BoxStation/BoxStation.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/MetaStation/MetaStation.dmm
The files from upstream mirror https://github.com/HippieStation/HippieStation/pull/6002#issuecomment-358724201 with less conflicts.
=> Upstream fix

_maps/map_files/HippieStation/hippiestation.dmm
added missing map changes from mirrors.
to cargo/circuitlab/techstorage/kitchen
Fixed some AT's around map
=> AT and mirror map fix

code/modules/mob/living/silicon/robot/robot.dm
:cl: Pyko
tweak: Enabled Clownborgs as an option for borgs modules.
/:cl:
HONK!
=> Enables Clownborgs

_maps/map_files/HippieStation/hippiestation.dmm
fixes https://github.com/HippieStation/HippieStation/issues/6227
Also fixes the circuitlab disposals not being connected.
cyberboss woz 'ere - praisenarsie
=> circuitlab map fixes

_maps/map_files/HippieStation/hippiestation.dmm
Pasted (hopefully) all of our changes in to current box map to update/fix things all around the station.
=> Hippiestation map update

_maps/map_files/PubbyStation/PubbyStation.dmm
https://github.com/HippieStation/HippieStation/pull/7147
=> Get our Pubby updated to current TG

code/modules/mob/living/carbon/human/human.dm
:cl: Pyko
fix: fixed the antigriff not applying properly.
/:cl:
=> Fixes a bug on autoadmin pt 1.

code/modules/mob/living/carbon/human/human.dm
Reverts HippieStation/HippieStation#7396
=> Revert "Fixes a bug on autoadmin pt 1."

code/controllers/subsystem/processing/traits.dm
:cl: Pyko
fix: fixed anti-griff system
/:cl:
=> Antigriff fix

hippiestation/code/modules/mob/living/carbon/human/species_types/avians.dm, hippiestation/code/modules/mob/living/carbon/human/species_types/ipcs.dm, hippiestation/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm, hippiestation/code/modules/mob/living/carbon/human/species_types/mothmen.dm, hippiestation/code/modules/mob/living/carbon/human/species_types/skeletons.dm, hippiestation/code/modules/mob/living/carbon/human/species_types/tarajans.dm
:cl: Pyko
fix: all (round start) races are equal
/:cl:
Fixes: https://github.com/HippieStation/HippieStation/issues/7557
=> Ends the racial bigotry

hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
:cl: 
fixes: Fixes vampire revive taking more than 1 minute
/:cl:
fixes #4324 
hi carbon : - )
=> Fixes vampires revive taking more than 1 minute

hippiestation/code/modules/clothing/outfits/standard.dm
:cl:
fix: Wizards and Apprentices now spawn with their emergency internal boxes.
/:cl:
[why]: i have big cock.. :pepegrim:
=> fixes empty wizard box

code/game/gamemodes/cult/cult.dm
:cl: karma and AnturK
fix: fixes cult causing secret to fail sometimes
/:cl:
=> fixes failure setting up secret

code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
:cl: karma
del: Re-removes war op pop limit
/:cl:
[why]: got removed in an upstream merge
=> Re-removes war op pop limit

code/game/gamemodes/nuclear/nuclear.dm
:cl: karma
fix: fixes nuke ops causing secret to fail
/:cl:
=> fixes nuke ops causing secret to fail

code/datums/mutations/hulk.dm
:cl: karma
balance: hulk has no antistun anymore
/:cl:
If this is merged I will rebalance hulk fully in a different PR but I dont want to do it now without knowing if it'll be accepted or not
=> Removes antistun from hulk - keeps wall punching

code/modules/research/designs/nanite_designs.dm
:cl: karma
del: removes adrenal nanites
/:cl:
[why]: they're antistuns for free aside R&D points
=> REMOVES FREE NO DOWNSIDE ADRENALS FROM R&D

hippiestation/code/modules/research/techweb/all_nodes.dm
=> Fix techwebs

hippiestation/code/game/machinery/computer/arcade.dm, hippiestation/code/game/objects/items/plushes.dm
:cl: karma
fix: goat plushie having TK
/:cl:
[why]: i forgot throwing doesn't always hit the target
=> Goat plushie nerf

code/modules/ruins/spaceruin_code/hilbertshotel.dm
=> fix hilberts hotel

hippiestation/code/game/objects/items/plushes.dm
=> fixes goat plushies for real

hippiestation/code/modules/uplink/uplink_items.dm
:cl: karma
del: Removes BlastCo temporarily
/:cl:
[why]: newbie bait as it's not in the map atm. if it bugs out it can fuck over a warops round.
=> comments out blastco

hippiestation/code/game/gamemodes/vampire/vampire.dm
:cl: karma
fix: fixed vamp gamemode not having a round start report
/:cl:
=> sadsddassda

code/modules/surgery/bodyparts/bodyparts.dm
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )
:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images …
=> Fixes legs

_maps/shuttles/emergency_big.dmm, config/unbuyableshuttles.txt, hippiestation/code/datums/shuttles.dm
:cl: karma
add: a new escape shuttle - "A Rather Large Escape Shuttle!"
/:cl:
disclaimer: not actually that large
is tested
=> [READY] A Rather Large Escape Shuttle

code/__DEFINES/mobs.dm
=> Removes hygiene

hippiestation/code/modules/events/holiday/vday.dm
:cl: Pyko
tweak: Carbon didin't get a date for valentines day,  and neither do you. Valentines day now has 0% chance of happening.
/:cl:
=> No Valentines day allowed

code/datums/mutations/hulk.dm
Reverts HippieStation/HippieStation#9697
=> Revert "Removes antistun from hulk - keeps wall punching"

hippiestation/code/modules/antagonists/changeling/powers/tiny_prick.dm
=> [s] CRITICAL ANTAG FIX

hippiestation/code/modules/mob/living/simple_animal/slime/powers.dm
fixes slimes being able to try and feed on beepsky
=> Fix slime on beepsky

code/modules/antagonists/devil/devil.dm
Changelog
:cl:
balance: Devils now ascend at 8 souls and become a true devil at 5, from 12 and 7 respectively.
balance: Devils can no longer have cremation as one of their banishment routines.
balance: Devils also now take shorter to ascend.
/:cl:
devils are way too rare on hippie and i'd like to see them played more and I have _never_ seen an ascended devil on hippie at all
=> Buff devil

code/modules/mob/living/carbon/human/life.dm
literal waste of cpu power and i'm sick of seeing stink lines on everyone
=> Removes hygiene for real

hippiestation/code/modules/mining/machine_bluespace.dm
:cl:
tweak: Added bananium to the bluespace miner.
/:cl:
Clowns shall help :flag_sd: to destroy :flag_il:
hyonk
=> Bananium in the miner

code/modules/mob/living/carbon/human/species.dm, hippiestation/code/game/objects/effects/decals/cleanable/humans.dm, hippiestation/code/modules/projectiles/projectile/bullets.dm
:cl:
tweak: Blood sprays from when you get shot stay up for longer now.
/:cl:
I think it looks Cooler™
looks cool, sorta like shit from a comic book
inshallah I will burn Marvel to the ground
=> Make blood splatters fly for longer

hippiestation/code/game/objects/items/forged_weapons.dm
:cl:
tweak: Our new and improved casings now change into the same caliber as the master one all at once!
/:cl:
2 days down the drain, thank you chad yoyo and chad Neo for putting up with my bitchass. This code was made by Neo.
eaugh oof my dick
=> Makes the forge bullets all change into the same caliber at once

hippiestation/interface/skin.dmf
:cl:
tweak: Made the floating text bigger.
/:cl:
looked poopy, had to fix it
=> Makes the font 1 pixel larger.

code/__DEFINES/mobs.dm, code/datums/components/wet_floor.dm, code/game/turfs/open/_open.dm
:cl:
tweak: Utilization of even smaller carbon particulates enhanced the lubing quality of our lube by over 200%! You have no escape now.
/:cl:
The branch name is named that because trying to figure out how slipping works sure felt like penis torture.
remember that video of a clown making a slip line to space and slipping sending you there? That's this.
=> Reverts Lube to old hippie's functionality
